apiVersion: v1
kind: PersistentVolume
metadata:
  name: jetstream-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/jetstream/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jetstream-data-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
